### ISSUE TITLE
a query

### ISSUE THREAD

**Issue by s384** [RubixPower/Yasiac-amd#1]
In which version of python is it developed?
In which distributions have you tried it?
I currently use Deepin, but I can't get it going, I'm trying with Python 3.8

![DeepinScreenshot_Seleccionar área_20200308143728](https://user-images.githubusercontent.com/29610669/76168048-5c2abb80-614a-11ea-8931-9bcd4579f790.png)

Sorry for my english, I'm learning. XD

**Comment by RubixPower** [comment]
Hello... your english is fine so don't be concerned about it too much.
Currently tested the app only on Arco (Arch based) with python 3.8.2 installed.
Also are you sure u have all dependencies installed ?

**Comment by s384** [comment]
yes, i have install all dependencies.
i test the app in uos (based debian 10) and it's work, but in deepin 15.11 (based debian 9) dosn't work.
It's a great job, congratulations
![photo_2020-03-08_16-13-30](https://user-images.githubusercontent.com/29610669/76169523-cd24a000-6157-11ea-9ff8-b977f66d2c1a.jpg)
![photo_2020-03-08_16-13-34](https://user-images.githubusercontent.com/29610669/76169524-ce55cd00-6157-11ea-80c4-1df4c04c0049.jpg)

PD: I have solved the first line of the error with `sudo apt install at-spi2-core`

**Comment by RubixPower** [comment]
I will fix the ram modules manufacturer checker and also i found the same solution and it shall be added to the dependencies. Also install the 32bit version which is `lib32-at-spi2-core`

**Comment by RubixPower** [comment]
@s384 does everything work ? cpu, gpu, ram info ? what about gpu fan control ?

**Comment by RubixPower** [comment]
Install `at-spi2-core` and `lib32-at-spi2-core`
